version:'3.9'
services:
  db:
    image: postres:15
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      -db_data:/var/lib/postgresgl/data
  
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    env_file: .env
    ports:
      - "{API_PORT}:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
  
  frontend:
    build:
      content: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file: .env
    ports:
      - "{FRONT_PORT}:5173"
    volumes:
      - ./frontend:/app
    depends_on: 
      - api
volumes:
  db_data: